/**
 * Example 4: Build-time Generated Schemas (Type-First Pattern)
 *
 * Part 2: Generated JSON schemas
 *
 * This file simulates what a build tool would generate from the types in
 * 04-types.ts. In practice, this file would be:
 * - Auto-generated by a build step
 * - Excluded from version control (or committed as a build artifact)
 * - Regenerated whenever the source types change
 *
 * The key insight is that SchemaProvider<T> links the generated schema
 * to the hand-written type, ensuring type safety across the boundary.
 */

import type { SchemaProvider } from "@dherman/sacp";
import type {
  Summary,
  AnalysisResult,
  Config,
  UserProfile,
} from "./04-types.js";

/**
 * SchemaProvider for Summary type.
 * @generated from src/04-types.ts
 */
export const SummarySchema: SchemaProvider<Summary> = {
  toJsonSchema: () => ({
    type: "object",
    properties: {
      title: {
        type: "string",
        description: "A brief title for the summary",
      },
      points: {
        type: "array",
        items: { type: "string" },
        description: "Key points from the content",
      },
      wordCount: {
        type: "number",
        description: "Approximate word count of the original content",
      },
    },
    required: ["title", "points", "wordCount"],
  }),
};

/**
 * SchemaProvider for AnalysisResult type.
 * @generated from src/04-types.ts
 */
export const AnalysisResultSchema: SchemaProvider<AnalysisResult> = {
  toJsonSchema: () => ({
    type: "object",
    properties: {
      sentiment: {
        type: "string",
        enum: ["positive", "negative", "neutral"],
        description: "Overall sentiment of the content",
      },
      confidence: {
        type: "number",
        minimum: 0,
        maximum: 1,
        description: "Confidence score between 0 and 1",
      },
      topics: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: {
              type: "string",
              description: "The topic name",
            },
            relevance: {
              type: "number",
              minimum: 0,
              maximum: 1,
              description: "Relevance score between 0 and 1",
            },
          },
          required: ["name", "relevance"],
        },
        description: "Topics identified in the content",
      },
    },
    required: ["sentiment", "confidence", "topics"],
  }),
};

/**
 * SchemaProvider for Config type.
 * @generated from src/04-types.ts
 */
export const ConfigSchema: SchemaProvider<Config> = {
  toJsonSchema: () => ({
    type: "object",
    properties: {
      temperature: {
        type: "number",
        minimum: 0,
        maximum: 2,
        default: 0.7,
        description: "Temperature setting (0-2), defaults to 0.7",
      },
      maxTokens: {
        type: "number",
        description: "Maximum tokens to generate",
      },
      systemPrompt: {
        type: "string",
        description: "System prompt to use",
      },
    },
    required: [],
  }),
};

/**
 * SchemaProvider for UserProfile type.
 * @generated from src/04-types.ts
 */
export const UserProfileSchema: SchemaProvider<UserProfile> = {
  toJsonSchema: () => ({
    type: "object",
    properties: {
      id: {
        type: "string",
        format: "uuid",
        description: "Unique identifier (UUID format)",
      },
      email: {
        type: "string",
        format: "email",
        description: "Email address",
      },
      website: {
        type: "string",
        format: "uri",
        description: "Website URL",
      },
      createdAt: {
        type: "string",
        format: "date-time",
        description: "Account creation timestamp (ISO 8601 format)",
      },
    },
    required: ["id", "email", "createdAt"],
  }),
};

/**
 * Example usage (requires a running conductor):
 *
 * ```typescript
 * import { connect } from "@dherman/patchwork";
 * import type { Summary } from "./04-types.js";
 * import { SummarySchema } from "./04-types.schemas.js";
 *
 * const patchwork = await connect(["sacp-conductor", "--agent", "claude"]);
 *
 * // The result is typed as Summary (from 04-types.ts)
 * // The schema comes from the generated file (04-types.schemas.ts)
 * const summary = await patchwork
 *   .think(SummarySchema)
 *   .text("Summarize this document:")
 *   .display(documentContents)
 *   .run();
 *
 * console.log(summary.title);       // string
 * console.log(summary.points);      // string[]
 * console.log(summary.wordCount);   // number
 *
 * patchwork.close();
 * ```
 */
