/**
 * Example 4: Build-time Generated Schemas (Type-First Pattern)
 *
 * Part 1: Hand-written TypeScript types
 *
 * This file contains hand-written TypeScript types. The companion file
 * (04-types.schemas.ts) contains the generated JSON schemas.
 *
 * In a real project, 04-types.schemas.ts would be generated by a build tool like:
 * - TypeSpec (https://typespec.io)
 * - ts-json-schema-transformer (https://www.npmjs.com/package/@nrfcloud/ts-json-schema-transformer)
 * - typescript-json-schema (https://github.com/YousefED/typescript-json-schema)
 *
 * Best for:
 * - Type-first development (TypeScript types are the source of truth)
 * - Large codebases with many types
 * - Teams that prefer to avoid runtime schema libraries
 * - Clean separation between hand-written and generated code
 */

/**
 * A summary of content.
 */
export interface Summary {
  /** A brief title for the summary */
  title: string;
  /** Key points from the content */
  points: string[];
  /** Approximate word count of the original content */
  wordCount: number;
}

/**
 * Result of sentiment analysis.
 */
export interface AnalysisResult {
  /** Overall sentiment of the content */
  sentiment: "positive" | "negative" | "neutral";
  /** Confidence score between 0 and 1 */
  confidence: number;
  /** Topics identified in the content */
  topics: Topic[];
}

/**
 * A topic with its relevance score.
 */
export interface Topic {
  /** The topic name */
  name: string;
  /** Relevance score between 0 and 1 */
  relevance: number;
}

/**
 * Configuration for LLM interactions.
 */
export interface Config {
  /** Temperature setting (0-2), defaults to 0.7 */
  temperature?: number;
  /** Maximum tokens to generate */
  maxTokens?: number;
  /** System prompt to use */
  systemPrompt?: string;
}

/**
 * A user profile with validated fields.
 */
export interface UserProfile {
  /** Unique identifier (UUID format) */
  id: string;
  /** Email address */
  email: string;
  /** Website URL */
  website?: string;
  /** Account creation timestamp (ISO 8601 format) */
  createdAt: string;
}
