import { describe, it } from "node:test";
import assert from "node:assert";
import type { Summary, AnalysisResult } from "./generator.js";
import {
  SummarySchema,
  AnalysisResultSchema,
} from "./generator.schemas.js";

/**
 * These tests verify that the auto-generated schemas correctly
 * represent the TypeScript types from generator.ts.
 *
 * The schemas are generated by: pnpm generate:schemas
 * which runs @dherman/build-schema-providers on the source types.
 */

describe("Example 4: Build-time generated schemas", () => {
  describe("SummarySchema", () => {
    it("should produce valid JSON Schema", () => {
      const schema = SummarySchema.toJsonSchema();

      assert.strictEqual(schema.type, "object");
      assert.ok(schema.properties);
      assert.ok(Array.isArray(schema.required));
      assert.ok((schema.required as string[]).includes("title"));
      assert.ok((schema.required as string[]).includes("points"));
      assert.ok((schema.required as string[]).includes("wordCount"));
    });

    it("should have correct property types matching TypeScript interface", () => {
      const schema = SummarySchema.toJsonSchema();
      const props = schema.properties!;

      assert.strictEqual(props.title.type, "string");
      assert.strictEqual(props.points.type, "array");
      assert.strictEqual(props.points.items?.type, "string");
      assert.strictEqual(props.wordCount.type, "number");
    });

    it("should include minimum constraint from JSDoc", () => {
      const schema = SummarySchema.toJsonSchema();
      const props = schema.properties!;

      assert.strictEqual(props.wordCount.minimum, 0);
    });

    it("should preserve descriptions from JSDoc", () => {
      const schema = SummarySchema.toJsonSchema();
      const props = schema.properties!;

      assert.strictEqual(props.title.description, "A brief title for the summary");
      assert.strictEqual(props.points.description, "Key points from the content");
    });

    it("should type-check against hand-written interface", () => {
      // This is a compile-time check: if the schema provider
      // doesn't match the Summary type, TypeScript will error
      const _provider: typeof SummarySchema = SummarySchema;

      // Simulate what patchwork.think() would return
      const mockResult: Summary = {
        title: "Test",
        points: ["point 1"],
        wordCount: 100,
      };

      assert.ok(mockResult.title);
    });
  });

  describe("AnalysisResultSchema", () => {
    it("should handle enum types", () => {
      const schema = AnalysisResultSchema.toJsonSchema();
      const sentimentSchema = schema.properties?.sentiment;

      assert.ok(sentimentSchema?.enum);
      assert.ok(sentimentSchema.enum.includes("positive"));
      assert.ok(sentimentSchema.enum.includes("negative"));
      assert.ok(sentimentSchema.enum.includes("neutral"));
    });

    it("should handle nested object arrays", () => {
      const schema = AnalysisResultSchema.toJsonSchema();
      const topicsSchema = schema.properties?.topics;

      assert.strictEqual(topicsSchema?.type, "array");
      assert.ok(topicsSchema?.items);
      assert.strictEqual(topicsSchema.items?.type, "object");
    });

    it("should include numeric constraints from JSDoc", () => {
      const schema = AnalysisResultSchema.toJsonSchema();

      assert.strictEqual(schema.properties?.confidence.minimum, 0);
      assert.strictEqual(schema.properties?.confidence.maximum, 1);
    });
  });

  describe("Type-first workflow", () => {
    it("should maintain type safety between source types and schemas", () => {
      const jsonSchema = SummarySchema.toJsonSchema();
      assert.ok(jsonSchema);

      const verifyType = <T>(_schema: { toJsonSchema(): unknown }): T => {
        return {} as T;
      };

      const result: Summary = verifyType<Summary>(SummarySchema);
      assert.ok(result !== undefined);
    });

    it("should demonstrate clean separation of concerns", () => {
      // generator.ts: Hand-written types with JSDoc annotations (source of truth)
      // generator.schemas.ts: Auto-generated by pnpm generate:schemas
      //
      // The SchemaProvider<T> interface bridges these:
      // - T comes from generator.ts (hand-written)
      // - toJsonSchema() returns the auto-generated schema

      const validateStructure = (schema: { toJsonSchema(): unknown }) => {
        const json = schema.toJsonSchema() as Record<string, unknown>;
        return json.type === "object" && json.properties !== undefined;
      };

      assert.ok(validateStructure(SummarySchema));
      assert.ok(validateStructure(AnalysisResultSchema));
    });
  });
});
